# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bordados_app.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(9, 10, 181, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.input_buscar = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.input_buscar.setObjectName("input_buscar")
        self.horizontalLayout.addWidget(self.input_buscar)
        self.btn_buscar = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_buscar.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btn_buscar.setObjectName("btn_buscar")
        self.horizontalLayout.addWidget(self.btn_buscar)
        self.select_categoria = QtWidgets.QComboBox(self.centralwidget)
        self.select_categoria.setGeometry(QtCore.QRect(10, 40, 181, 21))
        self.select_categoria.setObjectName("select_categoria")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(200, 540, 591, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_renombrar = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.btn_renombrar.setObjectName("btn_renombrar")
        self.horizontalLayout_2.addWidget(self.btn_renombrar)
        self.btn_categoria = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.btn_categoria.setObjectName("btn_categoria")
        self.horizontalLayout_2.addWidget(self.btn_categoria)
        self.btn_favorito = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.btn_favorito.setObjectName("btn_favorito")
        self.horizontalLayout_2.addWidget(self.btn_favorito)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(199, 10, 591, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_nombre = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_nombre.setFont(font)
        self.label_nombre.setObjectName("label_nombre")
        self.horizontalLayout_3.addWidget(self.label_nombre)
        self.label_categoria = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_categoria.setObjectName("label_categoria")
        self.horizontalLayout_3.addWidget(self.label_categoria)
        self.label_favorito = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_favorito.setObjectName("label_favorito")
        self.horizontalLayout_3.addWidget(self.label_favorito)
        self.image = QtWidgets.QLabel(self.centralwidget)
        self.image.setGeometry(QtCore.QRect(260, 70, 450, 450))
        self.image.setObjectName("image")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(5, 61, 191, 481))
        self.listWidget.setObjectName("listWidget")
        self.btn_carpetas = QtWidgets.QPushButton(self.centralwidget)
        self.btn_carpetas.setGeometry(QtCore.QRect(9, 542, 181, 31))
        self.btn_carpetas.setObjectName("btn_carpetas")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_buscar.setText(_translate("MainWindow", "Buscar"))
        self.btn_renombrar.setText(_translate("MainWindow", "Renombrar"))
        self.btn_categoria.setText(_translate("MainWindow", "Categoria"))
        self.btn_favorito.setText(_translate("MainWindow", "Favorito"))
        self.label_nombre.setText(_translate("MainWindow", "TextLabel"))
        self.label_categoria.setText(_translate("MainWindow", "TextLabel"))
        self.label_favorito.setText(_translate("MainWindow", "TextLabel"))
        self.image.setText(_translate("MainWindow", "TextLabel"))
        self.btn_carpetas.setText(_translate("MainWindow", "Carpetas"))
